name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Github Action f or wget
      uses: wei/wget@v1.1.1
      with:
        args: -O /home/runner/work/dsharpplus.nupkg https://nuget.emzi0767.com/api/v3/flatcontainer/dsharpplus/4.2.0-nightly-01022/dsharpplus.4.2.0-nightly-01022.nupkg
    - name: GitHub Action for wget
      uses: wei/wget@v1.1.1
      with:
        args: -O /home/runner/work/dsharpplus.interactivity.nupkg https://nuget.emzi0767.com/api/v3/flatcontainer/dsharpplus.interactivity/4.2.0-nightly-01022/dsharpplus.interactivity.4.2.0-nightly-01022.nupkg
    - name: GitHub Action for wget
      uses: wei/wget@v1.1.1
      with:
        args: -O /home/runner/work/dsharpplus.voicenext.nupkg https://nuget.emzi0767.com/api/v3/flatcontainer/dsharpplus.voicenext/4.2.0-nightly-01022/dsharpplus.voicenext.4.2.0-nightly-01022.nupkg
    - name: GitHub Action for wget
      uses: wei/wget@v1.1.1
      with:
        args: -O /home/runner/work/dsharpplus.slashcommands.nupkg https://nuget.emzi0767.com/api/v3/flatcontainer/dsharpplus.slashcommands/4.2.0-nightly-01022/dsharpplus.slashcommands.4.2.0-nightly-01022.nupkg
    - name: Install DSharpPlus Nightly packages
      run: nuget install /home/runner/work/dsharpplus.nupkg
    - name: Install DSharpPlus Nightly packages
      run: nuget install /home/runner/work/dsharpplus.interactivity.nupkg
    - name: Install DSharpPlus Nightly packages
      run: nuget install /home/runner/work/dsharpplus.voicenext.nupkg
    - name: Install DSharpPlus Nightly packages
      run: nuget install /home/runner/work/dsharpplus.slashcommands.nupkg
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
