name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Create all needed directories
      run: |
        mkdir /home/runner/work/download
        mkdir /home/runner/work/FossiumBot-Windows/
        mkdir /home/runner/work/FossiumBot-Windows/FossiumBot
        mkdir /home/runner/work/FossiumBot-Windows-32-bit/
        mkdir /home/runner/work/FossiumBot-Windows-32-bit/FossiumBot
        mkdir /home/runner/work/FossiumBot-Windows-ARM/
        mkdir /home/runner/work/FossiumBot-Windows-ARM/FossiumBot
        mkdir /home/runner/work/FossiumBot-Windows-ARM64/
        mkdir /home/runner/work/FossiumBot-Windows-ARM64/FossiumBot
        mkdir /home/runner/work/FossiumBot-Linux/
        mkdir /home/runner/work/FossiumBot-Linux/FossiumBot
        mkdir /home/runner/work/FossiumBot-Linux-ARM/
        mkdir /home/runner/work/FossiumBot-Linux-ARM/FossiumBot
        mkdir /home/runner/work/FossiumBot-OSX/
        mkdir /home/runner/work/FossiumBot-OSX/FossiumBot
        mkdir /home/runner/work/localnuget/
    - name: Download custom script
      run: wget -O /home/runner/work/DownloadLatestDSPnupkg https://gitlab.com/SKBotNL/fossium-stuff/-/raw/main/DownloadLatestDSPnupkg
    - name: Run custom script
      run: |
        chmod +x /home/runner/work/DownloadLatestDSPnupkg
        /home/runner/work/DownloadLatestDSPnupkg
    
    - name: Add all downloaded NuGet packages to local NuGet repository
      run: |
        nuget add /home/runner/work/download/dsharpplus.nupkg -source /home/runner/work/localnuget/
        nuget add /home/runner/work/download/dsharpplus.interactivity.nupkg -source /home/runner/work/localnuget/
        nuget add /home/runner/work/download/dsharpplus.lavalink.nupkg -source /home/runner/work/localnuget/
        nuget add /home/runner/work/download/dsharpplus.slashcommands.nupkg -source /home/runner/work/localnuget/
    - name: Download custom NuGet.Config
      run: wget -O NuGet.Config https://gitlab.com/SKBotNL/fossium-stuff/-/raw/main/NuGet.Config

    - name: Publish Windows
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true
    - name: Publish Windows 32-bit
      run: dotnet publish -c Release -r win-x86 -p:PublishSingleFile=true --self-contained true
    - name: Publish Windows ARM
      run: dotnet publish -c Release -r win-arm -p:PublishSingleFile=true --self-contained true
    - name: Publish Windows ARM64
      run: dotnet publish -c Release -r win-arm64 -p:PublishSingleFile=true --self-contained true
    - name: Publish Linux
      run: dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained true
    - name: Publish Linux ARM
      run: dotnet publish -c Release -r linux-arm -p:PublishSingleFile=true --self-contained true
    - name: Publish MacOS
      run: dotnet publish -c Release -r osx-x64 -p:PublishSingleFile=true --self-contained true
      
    - name: Remove unneeded .pdb files
      run: |
        rm /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/win-x64/publish/FossiumBot.pdb
        rm /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/win-x86/publish/FossiumBot.pdb
        rm /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/win-arm/publish/FossiumBot.pdb
        rm /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/win-arm64/publish/FossiumBot.pdb
        rm /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/linux-x64/publish/FossiumBot.pdb
        rm /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/linux-arm/publish/FossiumBot.pdb
        rm /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/osx-x64/publish/FossiumBot.pdb
    
    - name: Move files to their own directory
      run: |
        mv /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/win-x64/publish/* /home/runner/work/FossiumBot-Windows/FossiumBot
        mv /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/win-x86/publish/* /home/runner/work/FossiumBot-Windows-32-bit/FossiumBot
        mv /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/win-arm/publish/* /home/runner/work/FossiumBot-Windows-ARM/FossiumBot
        mv /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/win-arm64/publish/* /home/runner/work/FossiumBot-Windows-ARM64/FossiumBot
        mv /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/linux-x64/publish/* /home/runner/work/FossiumBot-Linux/FossiumBot
        mv /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/linux-arm/publish/* /home/runner/work/FossiumBot-Linux-ARM/FossiumBot
        mv /home/runner/work/FossiumBot/FossiumBot/FossiumBot/bin/Release/net6.0/osx-x64/publish/* /home/runner/work/FossiumBot-OSX/FossiumBot
    - name: Upload artifact Windows
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifact-win-x64
        path: /home/runner/work/FossiumBot-Windows/
    - name: Upload artifact Windows 32-bit
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifact-win-x86
        path: /home/runner/work/FossiumBot-Windows-32-bit/
    - name: Upload artifact Windows ARM
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifact-win-arm
        path: /home/runner/work/FossiumBot-Windows-ARM/
    - name: Upload artifact Windows ARM64
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifact-win-arm64
        path: /home/runner/work/FossiumBot-Windows-ARM64/
    - name: Upload artifact Linux
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifact-linux-x64
        path: /home/runner/work/FossiumBot-Linux/
    - name: Upload artifact Linux ARM
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifact-linux-arm
        path: /home/runner/work/FossiumBot-Linux-ARM/
    - name: Upload artifact MacOS
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifact-macos-x64
        path: /home/runner/work/FossiumBot-OSX/
